@startuml

Class Car {
    - color: String
    - battery: Battery
    - remoteControl: RemoteControl

    + Car(color: String, battery Battery, remoteControl RemoteControl): Car

    + setBattery(battery: Battery): void
    + setColor(newColor: String): void
    + setRemoteControl(remoteControl: RemoteControl): void

    + moveForward(distance: Integer): String
    + moveBackward(distance: Integer): String
    + stop(): String
    + turnLeft(): String
    + turnRight(): String
}

Class Battery {
    - type: String
    - remainingBatteryPercentage: Integer

    + Battery(type: String): Battery
    + getRemainingBatteryPercentage(): Integer
}

Class RemoteControl {
    - type: String

    + RemoteControl(type: String): RemoteControl

}

@enduml

